HOST: 0.0.0.0
INTERNAL_DIR: /archivy/.local/share/archivy
PANDOC_HIGHLIGHT_THEME: pygments
PORT: 5000
SEARCH_CONF:
  enabled: 1
  engine: elasticsearch
  index_name: dataobj
  search_conf:
    mappings:
      properties:
        body:
          analyzer: rebuilt_standard
          type: text
        tags:
          analyzer: rebuilt_standard
          type: text
        title:
          analyzer: rebuilt_standard
          term_vector: with_positions_offsets
          type: text
    settings:
      analysis:
        analyzer:
          rebuilt_standard:
            filter:
            - lowercase
            - kstem
            - trim
            - unique
            stopwords: _english_
            tokenizer: standard
      highlight:
        max_analyzed_offset: 100000000
  url: http://elasticsearch:9200
USER_DIR: /archivy/data
